import { useRouter } from 'expo-router';
import { signOut } from 'firebase/auth';
import { useState, useEffect } from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable, ActivityIndicator } from 'react-native';
import DashboardHeader from '../../components/sadmin/DashboardHeader';
import LogsFeed from '../../components/sadmin/LogsFeed';
import ProfileMenu from '../../components/sadmin/ProfileMenu';
import { auth } from '../../FirebaseConfig';
import ThemedView from '../../components/ThemedView';
import AppButton from '../../components/AppButton';
import AppToast from '../../components/AppToast';
import { fetchLogs, createLog, clearAllLogs } from '../../services/logService';
import AppTextField from '../../components/AppTextField';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';



export default function SuperAdminLogsScreen() {
    const router = useRouter();
    const [isProfileMenuOpen, setIsProfileMenuOpen] = useState(false);
    const [logs, setLogs] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [activeFilter, setActiveFilter] = useState('All');
    const [searchQuery, setSearchQuery] = useState('');
    
    // Action states
    const [isExporting, setIsExporting] = useState(false);
    const [isClearing, setIsClearing] = useState(false);
    const [toast, setToast] = useState({ message: '', type: 'error' });

    const loadLogs = async (filter) => {
        setIsLoading(true);
        try {
            const fetchedLogs = await fetchLogs(filter);
            setLogs(fetchedLogs);
        } catch (error) {
            console.error('Error fetching logs:', error);
            showToast('Failed to load logs');
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        loadLogs(activeFilter);
    }, [activeFilter]);

    const showToast = (message, type = 'error') => {
        setToast({ message, type });
    };

    const handleExportAudit = async () => {
        setIsExporting(true);
        try {
            const htmlContent = `
                <html>
                    <head>
                        <style>
                            body { font-family: 'Helvetica', sans-serif; padding: 20px; }
                            h1 { color: #1e3a8a; text-align: center; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
                            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
                            th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
                            th { background-color: #f3f4f6; color: #374151; }
                            .header-info { margin-bottom: 30px; font-size: 14px; }
                            .ERROR { color: #dc2626; font-weight: bold; }
                            .WARN { color: #d97706; font-weight: bold; }
                            .INFO { color: #059669; font-weight: bold; }
                        </style>
                    </head>
                    <body>
                        <h1>System Audit Report</h1>
                        <div class="header-info">
                            <p><strong>Generated By:</strong> SAdmin</p>
                            <p><strong>Date Generated:</strong> ${new Date().toLocaleString()}</p>
                            <p><strong>Total Logs Included:</strong> ${filteredLogs.length}</p>
                        </div>
                        <table>
                            <thead>
                                <tr>
                                    <th>Timestamp</th>
                                    <th>Level</th>
                                    <th>Actor</th>
                                    <th>Service</th>
                                    <th>Message</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${filteredLogs.map(log => `
                                    <tr>
                                        <td>${log.createdAt?.toDate ? log.createdAt.toDate().toLocaleString() : 'N/A'}</td>
                                        <td class="${log.level}">${log.level}</td>
                                        <td>${log.actor}</td>
                                        <td>${log.service}</td>
                                        <td>${log.message}</td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </body>
                </html>
            `;
            const { uri } = await Print.printToFileAsync({ html: htmlContent });
            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri);
            }
        } catch (error) {
            console.error('Error generating report:', error);
            showToast('Failed to generate audit report.');
        } finally {
            setIsExporting(false);
        }
    };

    const handleClearAllLogs = async () => {
        setIsClearing(true);
        try {
            await clearAllLogs();
            setLogs([]);
            showToast('All logs cleared successfully', 'success');
        } catch (error) {
            console.error('Error clearing logs:', error);
            showToast('Failed to clear logs');
        } finally {
            setIsClearing(false);
        }
    };

    const openProfileMenu = () => {
        setIsProfileMenuOpen(true);
    };

    const closeProfileMenu = () => {
        setIsProfileMenuOpen(false);
    };

    const handleSignOut = async () => {
        try {
            await signOut(auth);
            setIsProfileMenuOpen(false);
            router.replace('/');
        } catch (error) {
            console.error('Failed to sign out:', error);
        }
    };

    const filteredLogs = logs.filter(log => {
        if (!searchQuery) return true;
        const q = searchQuery.toLowerCase();
        return (
            (log.actor && log.actor.toLowerCase().includes(q)) ||
            (log.message && log.message.toLowerCase().includes(q)) ||
            (log.service && log.service.toLowerCase().includes(q))
        );
    });

    return (
        <ThemedView style={styles.container} safe>
            <AppToast
                message={toast.message}
                type={toast.type}
                onHide={() => setToast((prev) => ({ ...prev, message: '' }))}
            />

            {isProfileMenuOpen ? <Pressable style={styles.overlay} onPress={closeProfileMenu} /> : null}

            {isProfileMenuOpen ? (
                <View style={styles.profileMenuWrap}>
                    <ProfileMenu onSignOut={handleSignOut} />
                </View>
            ) : null}

            <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
                <DashboardHeader onProfilePress={openProfileMenu} title="Audit Center" subtitle="Security & Monitoring" />
                <Text style={styles.subtitle}>Track system events, filter by actor, and export compliance reports.</Text>
                
                <AppTextField
                    leftIconName="search"
                    leftIconColor="#667693"
                    value={searchQuery}
                    onChangeText={setSearchQuery}
                    placeholder="Search logs by actor, service, or message..."
                    placeholderTextColor="#667693"
                />

                <View style={styles.actionsRow}>
                    <AppButton 
                        title={isExporting ? "Exporting..." : "Export Audit Report"} 
                        onPress={handleExportAudit} 
                        disabled={isExporting || isClearing || filteredLogs.length === 0}
                        style={styles.actionButton}
                        iconName="document-text-outline"
                    />
                    <AppButton 
                        title={isClearing ? "Clearing..." : "Clear All Logs"} 
                        onPress={handleClearAllLogs} 
                        disabled={isClearing || isExporting || logs.length === 0}
                        style={[styles.actionButton, styles.dangerButton]}
                        textStyle={styles.dangerButtonText}
                        iconName="trash-outline"
                    />
                </View>

                {isLoading ? (
                    <ActivityIndicator size="small" color="#667693" style={{ marginTop: 20 }} />
                ) : filteredLogs.length === 0 ? (
                    <>
                        <LogsFeed logs={[]} activeFilter={activeFilter} onFilterChange={setActiveFilter} />
                        <Text style={styles.emptyText}>No logs found for this filter.</Text>
                    </>
                ) : (
                    <LogsFeed logs={filteredLogs} activeFilter={activeFilter} onFilterChange={setActiveFilter} />
                )}
            </ScrollView>
        </ThemedView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#020b24',
        position: 'relative',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 20,
    },
    profileMenuWrap: {
        position: 'absolute',
        top: 96,
        right: 16,
        zIndex: 30,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 24,
        gap: 12,
    },
    subtitle: {
        color: '#8da2c0',
        fontSize: 14,
        marginTop: 2,
    },
    actionsRow: {
        flexDirection: 'row',
        gap: 10,
        marginVertical: 10,
    },
    actionButton: {
        flex: 1,
        height: 48,
        marginVertical: 0,
    },
    dangerButton: {
        backgroundColor: 'rgba(239,68,68,0.1)',
        borderColor: 'rgba(239,68,68,0.3)',
    },
    dangerButtonText: {
        color: '#ff6b76',
    },
    emptyText: {
        color: '#8da2c0',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 20,
    },
});
